schema_version = "1.0.0"
id = "sansar_tools_vat"
version = "1.3.0"
name = "Sansar Tools - VAT Generator"
tagline = "Add-on to generate Vertex Animated Textures for Sansar"
maintainer = "Tensor"
type = "add-on"
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]
website = "https://github.com/TENS0R/Sansar-Blender-Tools"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".*",
  "*.zip",
  "README.md",
  "releases/",
]